name: Deploy Calastone

on:
  push:
    branches:
      - main

jobs:
    security_scan:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v1.6.0

    build-and-deploy:
      runs-on: ubuntu-22.04

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            export_default_credentials: true

        - name: Configure Docker to use Google Artifact Registry
          run: gcloud auth configure-docker us-central1-docker.pkg.dev

        - name: Verify Docker authentication
          run: docker info

        - name: Verify authentication to Artifact Registry
          run: gcloud auth list

        - name: Build Docker image
          run: docker build -t us-central1-docker.pkg.dev/master-253005/nydalprojects/my-app:latest .

        - name: Push Docker image
          run: docker push us-central1-docker.pkg.dev/master-253005/nydalprojects/my-app:latest

        - name: Deploy to Cloud Run
          run: |
            gcloud run deploy my-cloud-run-service \
              --image us-central1-docker.pkg.dev/master-253005/nydalprojects/my-app:latest \
              --region us-central1 \
              --platform managed \
              --allow-unauthenticated \
              --port 8080 \
              --memory 256Mi \
              --cpu 1